sudo: required

services:
  - docker

install:
  - docker build --tag bodsch/docker-markdownd .
  - docker run --detach --name markdownd bodsch/docker-markdownd

script:
  - docker ps | grep -q markdownd

after_success:
  - |
    [ "${TRAVIS_BRANCH}" == "master" ] && curl \
      --request POST \
      --header "Content-Type: application/json"  \
      --data '{"source_type":"Branch","source_name":"master"}' \
      https://registry.hub.docker.com/u/bodsch/docker-markdownd/trigger/${DOCKER_HUB_TOKEN}/
